### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [omniorb/omniifr#3]
I would like to point out that an identifier like “[`OMNIIFR__DEPENDENCY_H`](https://github.com/omniorb/omniifr/blob/17774d1492df9bbf41f6c100910d1784abc3aff3/repository/Dependency.h#L23-L24 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mfld-fr** [comment]
Hello, thanks for the feedback. I am sorry to not understand why this identifier, without a leading underscore, is not compliant to the C++ standard ? Could you please elaborate ?

**Comment by elfring** [comment]
* :eyes: Please take another look at [name conventions](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
  How do you think about to avoid that this software [depends on undefined behaviour](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Documentation")? :thinking:
* :thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html "Checking the application of reserved identifiers")?

**Comment by mfld-fr** [comment]
- OK, got it : you are dealing with the "adjacent underscores ", right ?
- Yes, I am interested in any tool that could be easily be integrated into this project to statically check the code.

**Comment by elfring** [comment]
:thought_balloon: I propose to reconsider also the usage of (double) underscores for some identifiers.
:crystal_ball: Will development interests accordingly grow to increase the compliance with the C++ language standard?

**Comment by mfld-fr** [comment]
It appears that the previous posts are generated by a kind of bot --> closing this issue.

**Comment by elfring** [comment]
>It appears that the previous posts are generated by a kind of bot …

:thought_balloon: Please reconsider such a view!
